version: '3.7'
services:
 ldap_server:
    image: niklas/ldap-dev:latest
    build: .
    environment:
      LDAP_ADMIN_PASSWORD: Niklas12
      LDAP_BASE_DN: dc=niklas,dc=tech
    ports:
      - 389:389
    volumes:
      - ldapdata:/var/lib/ldap
      - ldapconfig:/etc/ldap/slapd.d
 ldap_server_admin:
    image: osixia/phpldapadmin:0.7.2
    ports:
      - 7999:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'
volumes:
  ldapdata:
  ldapconfig:
